-- MySQL Script generated by MySQL Workbench
-- utorak, 12. decembar 2017. 15:22:52 cet
-- Model: New Model    version: 1.0
-- MySQL Workbench Forward Engineering

set @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
set @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
set @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema formula4000
-- -----------------------------------------------------
drop schema if exists `formula4000` ;

-- -----------------------------------------------------
-- Schema formula4000
-- -----------------------------------------------------
create schema if not exists `formula4000` default character set UTF8 ;
use `formula4000` ;

-- -----------------------------------------------------
-- Table `formula4000`.`motor`
-- -----------------------------------------------------
drop table if exists `formula4000`.`motor` ;

create table if not exists `formula4000`.`motor` (
  `broj_motora` int not null,
  `proizvodjac` varchar(45) not null,
  `zapremina` smallint not null,
  `radna_temperatura` smallint not null,
  `snaga` smallint not null,
  `broj_obrtaja` smallint not null,
  `pouzdanost` varchar(45) null,
  primary key (`broj_motora`))
engine = InnoDB;


-- -----------------------------------------------------
-- Table `formula4000`.`tim`
-- -----------------------------------------------------
drop table if exists `formula4000`.`tim` ;

create table if not exists `formula4000`.`tim` (
  `id_tima` int not null auto_increment,
  `ime` varchar(45) not null,
  primary key (`id_tima`),
  unique index `ime_unique` (`ime` asc))
engine = InnoDB;


-- -----------------------------------------------------
-- Table `formula4000`.`formula`
-- -----------------------------------------------------
drop table if exists `formula4000`.`formula` ;

create table if not exists `formula4000`.`formula` (
  `broj_sasije` int not null,
  `proizvodjac` varchar(45) not null,
  `maks_brzina` smallint not null,
  `tezina` smallint not null,
  `duzina` smallint not null,
  `motor` int not null,
  `tim` int not null,
  primary key (`broj_sasije`),
  index `fk_formula_motor_idx` (`motor` asc),
  index `fk_formula_tim_idx` (`tim` asc),
  unique index `motor_unique` (`motor` asc),
  constraint `fk_formula_motor`
    foreign key (`motor`)
    references `formula4000`.`motor` (`broj_motora`)
    on delete cascade
    on update cascade,
  constraint `fk_formula_tim`
    foreign key (`tim`)
    references `formula4000`.`tim` (`id_tima`)
    on delete cascade
    on update cascade)
engine = InnoDB;


-- -----------------------------------------------------
-- Table `formula4000`.`paket_guma`
-- -----------------------------------------------------
drop table if exists `formula4000`.`paket_guma` ;

create table if not exists `formula4000`.`paket_guma` (
  `formula` int not null,
  `proizvodjac` varchar(45) not null,
  `tip` varchar(45) not null,
  `velicina` smallint not null,
  `radna_temperatura` smallint not null,
  `trajanje` smallint null,
  primary key (`formula`),
  constraint `fk_paket_guma_formula`
    foreign key (`formula`)
    references `formula4000`.`formula` (`broj_sasije`)
    on delete cascade
    on update cascade)
engine = InnoDB;


-- -----------------------------------------------------
-- Table `formula4000`.`menadzer`
-- -----------------------------------------------------
drop table if exists `formula4000`.`menadzer` ;

create table if not exists `formula4000`.`menadzer` (
  `id_menadzera` int not null auto_increment,
  `ime` varchar(45) not null,
  `veze` smallint null,
  primary key (`id_menadzera`))
engine = InnoDB;


-- -----------------------------------------------------
-- Table `formula4000`.`vozac`
-- -----------------------------------------------------
drop table if exists `formula4000`.`vozac` ;

create table if not exists `formula4000`.`vozac` (
  `id_vozaca` int not null auto_increment,
  `ime` varchar(45) not null,
  `prezime` varchar(45) not null,
  `godina_rodjenja` smallint not null,
  `visina` smallint not null,
  `tezina` smallint not null,
  `formula` int null,
  `menadzer` int null,
  `tim` int null,
  primary key (`id_vozaca`),
  index `fk_vozac_formula_idx` (`formula` asc),
  index `fk_vozac_menadzer_idx` (`menadzer` asc),
  index `fk_vozac_tim_idx` (`tim` asc),
  constraint `fk_vozac_formula`
    foreign key (`formula`)
    references `formula4000`.`formula` (`broj_sasije`)
    on delete set null
    on update cascade,
  constraint `fk_vozac_menadzer`
    foreign key (`menadzer`)
    references `formula4000`.`menadzer` (`id_menadzera`)
    on delete set null
    on update cascade,
  constraint `fk_vozac_tim`
    foreign key (`tim`)
    references `formula4000`.`tim` (`id_tima`)
    on delete set null
    on update cascade)
engine = InnoDB;


-- -----------------------------------------------------
-- Table `formula4000`.`staza`
-- -----------------------------------------------------
drop table if exists `formula4000`.`staza` ;

create table if not exists `formula4000`.`staza` (
  `redni_broj` int not null auto_increment,
  `lokacija` varchar(45) not null,
  `broj_krugova` smallint not null,
  `duzina_kruga` smallint not null,
  `broj_krivina` smallint null,
  `mesta_za_preticanje` smallint null,
  primary key (`redni_broj`))
engine = InnoDB;


-- -----------------------------------------------------
-- Table `formula4000`.`sponzor`
-- -----------------------------------------------------
drop table if exists `formula4000`.`sponzor` ;

create table if not exists `formula4000`.`sponzor` (
  `id_sponzora` int not null auto_increment,
  `ime` varchar(45) not null,
  `marketing` varchar(45) not null,
  `brend` varchar(45) not null,
  primary key (`id_sponzora`))
engine = InnoDB;


-- -----------------------------------------------------
-- Table `formula4000`.`sponzorski_pul`
-- -----------------------------------------------------
drop table if exists `formula4000`.`sponzorski_pul` ;

create table if not exists `formula4000`.`sponzorski_pul` (
  `id_tima` int not null,
  `id_sponzora` int not null,
  `trajanje` smallint null,
  primary key (`id_tima`, `id_sponzora`),
  index `fk_sponzorski_pul_sponzor_idx` (`id_sponzora` asc),
  constraint `fk_sponzorski_pul_tim`
    foreign key (`id_tima`)
    references `formula4000`.`tim` (`id_tima`)
    on delete cascade
    on update cascade,
  constraint `fk_sponzorski_pul_sponzor`
    foreign key (`id_sponzora`)
    references `formula4000`.`sponzor` (`id_sponzora`)
    on delete cascade
    on update cascade)
engine = InnoDB;


-- -----------------------------------------------------
-- Table `formula4000`.`vlasnik`
-- -----------------------------------------------------
drop table if exists `formula4000`.`vlasnik` ;

create table if not exists `formula4000`.`vlasnik` (
  `id_vlasnika` int not null auto_increment,
  `ime` varchar(45) not null,
  `prezime` varchar(45) not null,
  `saldo` smallint not null,
  `kriminalna_proslost` varchar(45) not null,
  `redovna_isplata` varchar(45) null,
  primary key (`id_vlasnika`))
engine = InnoDB;


-- -----------------------------------------------------
-- Table `formula4000`.`vlasnistvo`
-- -----------------------------------------------------
drop table if exists `formula4000`.`vlasnistvo` ;

create table if not exists `formula4000`.`vlasnistvo` (
  `id_tima` int not null,
  `id_vlasnika` int not null,
  `trajanje` smallint null,
  primary key (`id_tima`, `id_vlasnika`),
  index `fk_vlasnistvo_vlasnik_idx` (`id_vlasnika` asc),
  constraint `fk_vlasnistvo_tim`
    foreign key (`id_tima`)
    references `formula4000`.`tim` (`id_tima`)
    on delete cascade
    on update cascade,
  constraint `fk_vlasnistvo_vlasnik`
    foreign key (`id_vlasnika`)
    references `formula4000`.`vlasnik` (`id_vlasnika`)
    on delete cascade
    on update cascade)
engine = InnoDB;


-- -----------------------------------------------------
-- Table `formula4000`.`mehanicar`
-- -----------------------------------------------------
drop table if exists `formula4000`.`mehanicar` ;

create table if not exists `formula4000`.`mehanicar` (
  `broj_licence` int not null,
  `ime` varchar(45) not null,
  `prezime` varchar(45) not null,
  `struka` varchar(45) not null,
  `staz` smallint not null,
  `prethodni_poslovi` smallint null,
  primary key (`broj_licence`))
engine = InnoDB;


-- -----------------------------------------------------
-- Table `formula4000`.`odrzavanje`
-- -----------------------------------------------------
drop table if exists `formula4000`.`odrzavanje` ;

create table if not exists `formula4000`.`odrzavanje` (
  `id_tima` int not null,
  `id_mehanicara` int not null,
  `poslednji_servis` datetime null,
  primary key (`id_tima`, `id_mehanicara`),
  index `fk_odrzavanje_mehanicar_idx` (`id_mehanicara` asc),
  constraint `fk_odrzavanje_tim`
    foreign key (`id_tima`)
    references `formula4000`.`tim` (`id_tima`)
    on delete cascade
    on update cascade,
  constraint `fk_odrzavanje_mehanicar`
    foreign key (`id_mehanicara`)
    references `formula4000`.`mehanicar` (`broj_licence`)
    on delete cascade
    on update cascade)
engine = InnoDB;


-- -----------------------------------------------------
-- Table `formula4000`.`prvenstvo`
-- -----------------------------------------------------
drop table if exists `formula4000`.`prvenstvo` ;

create table if not exists `formula4000`.`prvenstvo` (
  `id_prvenstva` int not null auto_increment,
  `naziv` varchar(45) not null,
  `broj_timova` smallint not null,
  `broj_staza` smallint not null,
  `popularnost` varchar(45) null,
  primary key (`id_prvenstva`),
  unique index `naziv_unique` (`naziv` asc))
engine = InnoDB;


-- -----------------------------------------------------
-- Table `formula4000`.`trka`
-- -----------------------------------------------------
drop table if exists `formula4000`.`trka` ;

create table if not exists `formula4000`.`trka` (
  `id_staze` int not null,
  `id_prvenstva` int not null,
  `vreme_odrzavanja` datetime null,
  `pobednicki_tim` int null,
  primary key (`id_staze`, `id_prvenstva`),
  index `fk_trka_prvenstvo_idx` (`id_prvenstva` asc),
  index `fk_trka_pobednik_idx` (`pobednicki_tim` asc),
  constraint `fk_trka_staza`
    foreign key (`id_staze`)
    references `formula4000`.`staza` (`redni_broj`)
    on delete cascade
    on update cascade,
  constraint `fk_trka_prvenstvo`
    foreign key (`id_prvenstva`)
    references `formula4000`.`prvenstvo` (`id_prvenstva`)
    on delete cascade
    on update cascade,
  constraint `fk_trka_pobednik`
    foreign key (`pobednicki_tim`)
    references `formula4000`.`tim` (`id_tima`)
    on delete set null
    on update cascade)
engine = InnoDB;


-- -----------------------------------------------------
-- Table `formula4000`.`ucestvovanje`
-- -----------------------------------------------------
drop table if exists `formula4000`.`ucestvovanje` ;

create table if not exists `formula4000`.`ucestvovanje` (
  `id_tima` int not null,
  `id_prvenstva` int not null,
  primary key (`id_tima`, `id_prvenstva`),
  index `fk_ucestvovanje_prvenstvo_idx` (`id_prvenstva` asc),
  constraint `fk_ucestvovanje_tim`
    foreign key (`id_tima`)
    references `formula4000`.`tim` (`id_tima`)
    on delete cascade
    on update cascade,
  constraint `fk_ucestvovanje_prvenstvo`
    foreign key (`id_prvenstva`)
    references `formula4000`.`prvenstvo` (`id_prvenstva`)
    on delete cascade
    on update cascade)
engine = InnoDB;


set SQL_MODE=@OLD_SQL_MODE;
set FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
set UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
use `formula4000`;

delimiter $$

use `formula4000`$$
drop trigger if exists `formula4000`.`formula_before_insert` $$
use `formula4000`$$
create trigger `formula4000`.`formula_before_insert` before insert on `formula` for each row
begin
	if new.motor in (select motor from formula) then
		signal sqlstate '45000' set message_text='Motor je vec pridruzen nekoj formuli!';
	end if;
end$$


use `formula4000`$$
drop trigger if exists `formula4000`.`formula_before_update` $$
use `formula4000`$$
create trigger `formula4000`.`formula_before_update` before update on `formula` for each row
begin
	if new.motor in (select motor from formula) then
		signal sqlstate '45000' set message_text='Motor je vec pridruzen nekoj formuli!';
	end if;
end$$


use `formula4000`$$
drop trigger if exists `formula4000`.`vozac_before_insert` $$
use `formula4000`$$
create trigger `formula4000`.`vozac_before_insert` before insert on `vozac` for each row
begin
	if (new.formula not in (select broj_sasije from formula where tim=new.tim)) then
		signal sqlstate '45000' set message_text='Vozac mora voziti formulu koja pripada njegovom timu!';
	end if;
end$$


use `formula4000`$$
drop trigger if exists `formula4000`.`vozac_before_update` $$
use `formula4000`$$
create trigger `formula4000`.`vozac_before_update` before update on `vozac` for each row
begin
	if (new.formula not in (select broj_sasije from formula where tim=new.tim)) then
		signal sqlstate '45000' set message_text='Vozac mora voziti formulu koja pripada njegovom timu!';
	end if;
end$$


use `formula4000`$$
drop trigger if exists `formula4000`.`trka_before_insert` $$
use `formula4000`$$
create trigger `formula4000`.`trka_before_insert` before insert on `trka` for each row
begin
	set new.pobednicki_tim=null;
	if (select count(*)
		from trka
		where id_prvenstva=new.id_prvenstva)=(select broj_staza
							from prvenstvo as p
							where p.id_prvenstva=new.id_prvenstva) then
		signal sqlstate '45000' set message_text='Unet je maksimalan broj trka za ovo prvenstvo!';
	end if;
end$$


use `formula4000`$$
drop trigger if exists `formula4000`.`trka_before_update` $$
use `formula4000`$$
create trigger `formula4000`.`trka_before_update` before update on `trka` for each row
begin
	if new.pobednicki_tim not in (select u.id_tima
					from ucestvovanje as u
					where u.id_prvenstva=new.id_prvenstva) then
		signal sqlstate '45000' set message_text='Tim ne ucesvuje na ovom prvenstvu!';
	end if;
	if (select count(*)
		from trka
		where id_prvenstva=new.id_prvenstva)=(select broj_staza
							from prvenstvo as p
							where p.id_prvenstva=new.id_prvenstva) then
		signal sqlstate '45000' set message_text='Unet je maksimalan broj trka za ovo prvenstvo!';
	end if;
end$$


use `formula4000`$$
drop trigger if exists `formula4000`.`ucestvovanje_before_insert` $$
use `formula4000`$$
create trigger `formula4000`.`ucestvovanje_before_insert` before insert on `ucestvovanje` for each row
begin
	if (select count(*)
		from ucestvovanje
		where id_prvenstva=new.id_prvenstva)=(select broj_staza
							from prvenstvo as p
							where p.id_prvenstva=new.id_prvenstva) then
		signal sqlstate '45000' set message_text='Unet je maksimalan broj timova za ovo prvenstvo!';
	end if;
end$$


use `formula4000`$$
drop trigger if exists `formula4000`.`ucestvovanje_before_update` $$
use `formula4000`$$
create trigger `formula4000`.`ucestvovanje_before_update` before update on `ucestvovanje` for each row
begin
	if (select count(*)
		from ucestvovanje
		where id_prvenstva=new.id_prvenstva)=(select broj_staza
							from prvenstvo as p
							where p.id_prvenstva=new.id_prvenstva) then
		signal sqlstate '45000' set message_text='Unet je maksimalan broj timova za ovo prvenstvo!';
	end if;
end$$


delimiter ;
